#!/bin/bash
# ============================================================================
# MELP Module Linker - YZ_120
# ============================================================================
# Purpose: Combine multiple .mlp modules into a single compilable file
# Usage: ./link_modules.sh output.mlp module1.mlp module2.mlp ...
# ============================================================================

set -e

if [ "$#" -lt 2 ]; then
    echo "Usage: $0 <output.mlp> <module1.mlp> [module2.mlp ...]"
    echo ""
    echo "Example:"
    echo "  $0 combined.mlp core/char_utils.mlp lexer/lexer_main.mlp"
    exit 1
fi

OUTPUT="$1"
shift

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  MELP Module Linker - YZ_120${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Create header
echo -e "${GREEN}Creating combined module: ${OUTPUT}${NC}"
cat > "$OUTPUT" << 'EOF'
-- ============================================================================
-- MELP Combined Module - Auto-generated by link_modules.sh
-- ============================================================================
-- WARNING: This file is auto-generated. Do not edit manually.
-- Generated on: $(date)
-- ============================================================================

EOF

MODULE_COUNT=0

# Combine all modules
for MODULE in "$@"; do
    if [ ! -f "$MODULE" ]; then
        echo -e "${YELLOW}⚠ Warning: Module not found: ${MODULE}${NC}"
        continue
    fi
    
    MODULE_COUNT=$((MODULE_COUNT + 1))
    
    echo -e "${GREEN}[${MODULE_COUNT}] Adding module: ${MODULE}${NC}"
    
    # Add separator comment
    echo "" >> "$OUTPUT"
    echo "-- ============================================================================" >> "$OUTPUT"
    echo "-- MODULE ${MODULE_COUNT}: ${MODULE}" >> "$OUTPUT"
    echo "-- ============================================================================" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    
    # Filter out import statements and add module content
    grep -v "^import " "$MODULE" >> "$OUTPUT" || true
    
done

echo ""
echo -e "${GREEN}✅ Module linking complete!${NC}"
echo -e "${GREEN}   Output: ${OUTPUT}${NC}"
echo -e "${GREEN}   Modules combined: ${MODULE_COUNT}${NC}"
echo ""
echo -e "${BLUE}Next step: Compile with Stage 1${NC}"
echo -e "  ./compile_mlp.sh ${OUTPUT} output_binary${NC}"
