#!/bin/bash
# Stage1 Unified Build Script
# Merges all Stage1 modules into single C file

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GEN_DIR="$SCRIPT_DIR/generated"
OUT_DIR="$SCRIPT_DIR/bin"
UNIFIED_FILE="$OUT_DIR/stage1_unified.c"

echo "=== Stage1 Unified Build ==="
echo "Generated files: $GEN_DIR"
echo "Output: $UNIFIED_FILE"
echo ""

# Create output directory
mkdir -p "$OUT_DIR"

# Remove old unified file
rm -f "$UNIFIED_FILE"

# Write header comment
cat > "$UNIFIED_FILE" << 'EOF'
// ============================================================================
// MLP-GCC Stage1 Unified Build
// ============================================================================
// This file contains all Stage1 modules merged in dependency order
// Generated by: build_unified.sh
// Target: GCC C99
// ============================================================================

EOF

# Add common headers (only once)
cat >> "$UNIFIED_FILE" << 'EOF'
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

// STO Runtime types
typedef struct { /* bigdecimal */ } mlp_bigdecimal_t;
typedef struct { char* data; size_t len; } mlp_string_t;

EOF

# Function to strip headers from C file and append body
strip_and_append() {
    local file="$1"
    echo "// ============================================================================" >> "$UNIFIED_FILE"
    echo "// Module: $file" >> "$UNIFIED_FILE"
    echo "// ============================================================================" >> "$UNIFIED_FILE"
    echo "" >> "$UNIFIED_FILE"
    
    # Skip headers (#include, initial comments) and append rest
    sed '/^#include/d; /^\/\/ MLP-GCC Generated/d; /^\/\/ Target:/d; /^\/\/ STO:/d; /^typedef struct.*mlp_bigdecimal/d; /^typedef struct.*mlp_string/d' "$GEN_DIR/$file" >> "$UNIFIED_FILE"
    echo "" >> "$UNIFIED_FILE"
}

echo "Merging modules in dependency order..."

# Dependency order (base types first, main last)
MODULES=(
    "token_types.c"
    "gc_integration.c"
    "lexer.c"
    "parser.c"
    "parser_functions.c"
    "parser_structures.c"
    "parser_advanced.c"
    "scope_manager.c"
    "function_registry.c"
    "codegen.c"
    "codegen_functions.c"
    "codegen_control.c"
    "codegen_lambda.c"
    "codegen_async.c"
    "codegen_structures.c"
    "import_handler.c"
    "mlp_compiler_main.c"
)

for module in "${MODULES[@]}"; do
    if [ -f "$GEN_DIR/$module" ]; then
        echo "  + $module"
        strip_and_append "$module"
    else
        echo "  ! WARNING: $module not found, skipping"
    fi
done

echo ""
echo "✅ Unified file created: $UNIFIED_FILE"
echo "Size: $(wc -l < "$UNIFIED_FILE") lines"
echo ""
echo "Compiling Stage1..."

# Compile unified file
gcc -Wall -Wno-unused-function -Wno-unused-variable \
    "$UNIFIED_FILE" \
    -o "$OUT_DIR/melpc_stage1" \
    -lm

if [ $? -eq 0 ]; then
    echo ""
    echo "🎉 Stage1 compilation successful!"
    echo "Binary: $OUT_DIR/melpc_stage1"
    ls -lh "$OUT_DIR/melpc_stage1"
else
    echo ""
    echo "❌ Compilation failed"
    exit 1
fi
