#!/bin/bash
# Turkish to English Comment Translation Script
# Generated: December 16, 2025

# Translation map (Turkish → English)
declare -A TRANSLATIONS=(
    # Common programming terms
    ["Parametre sayısı"]="Parameter count"
    ["Değer ile capture"]="Capture by value"
    ["Lambda gövdesi"]="Lambda body"
    ["Henüz tamamlanmadı"]="Not yet completed"
    ["Şu anda çalışıyor"]="Currently running"
    ["Başarıyla tamamlandı"]="Successfully completed"
    ["Hata ile tamamlandı"]="Completed with error"
    ["İptal edildi"]="Cancelled"
    ["Bağımlılık sayısı"]="Dependency count"
    ["Ayırma stratejisi"]="Allocation strategy"
    ["Dosya adı"]="Filename"
    ["Açma modu"]="Open mode"
    ["Future durumları"]="Future states"
    ["Promise durumları"]="Promise states"
    ["Async fonksiyon türü"]="Async function type"
    ["Await operasyonu türü"]="Await operation type"
    ["Henüz yerine getirilmedi"]="Not yet fulfilled"
    ["Başarıyla yerine getirildi"]="Successfully fulfilled"
    ["Tüm future'ları bekle"]="Wait for all futures"
    ["İlk tamamlananı al"]="Get first completed"
    ["Boşta"]="Idle"
    ["Çalışıyor"]="Running"
    ["Gelecekteki bir değeri temsil eder"]="Represents a future value"
    ["Sonuç değeri"]="Result value"
    ["İlişkili promise"]="Associated promise"
    ["İlişkili task"]="Associated task"
    ["Bağımlı future'lar"]="Dependent futures"
    ["Eleman sayısı"]="Element count"
    ["Değişken adı"]="Variable name"
    ["Capture edilmiş değişkenler"]="Captured variables"
    ["Parametre adları"]="Parameter names"
    ["Dönüş future'ı"]="Return future"
    ["Generator mı?"]="Is generator?"
    ["Yield state (generator için)"]="Yield state (for generator)"
    ["Beklenen hedef (Future/Promise/değer)"]="Target to await (Future/Promise/value)"
    ["Çoklu hedefler (await_all, await_any)"]="Multiple targets (await_all, await_any)"
    ["Hedef sayısı"]="Target count"
    ["Timeout süresi (opsiyonel)"]="Timeout duration (optional)"
    ["İptal edilebilir mi?"]="Is cancellable?"
    ["Executor tarafından çalıştırılacak görev"]="Task to be executed by executor"
    ["Çalıştırılacak fonksiyon"]="Function to execute"
    ["Fonksiyon argümanları"]="Function arguments"
    ["Argüman sayısı"]="Argument count"
    ["Task'ın future'ı"]="Task's future"
    ["Child sayısı"]="Child count"
    ["Öncelik"]="Priority"
    ["Çalışıyor mu?"]="Is running?"
    ["Task'ları çalıştırır"]="Executes tasks"
    ["Çalıştırma stratejisi"]="Execution strategy"
    ["Task kuyruğu"]="Task queue"
    ["Thread sayısı (pool için)"]="Thread count (for pool)"
    ["İlişkili event loop"]="Associated event loop"
    ["Async işlemleri koordine eder"]="Coordinates async operations"
    ["İlişkili executor"]="Associated executor"
    ["Hazır task'lar"]="Ready tasks"
    ["Hazır task sayısı"]="Ready task count"
    ["Bekleyen task sayısı"]="Waiting task count"
    ["Tick sayısı"]="Tick count"
    ["Durmalı mı?"]="Should stop?"
    ["Tüm async sistemi yönetir"]="Manages entire async system"
    ["Future sayısı"]="Future count"
    ["Promise sayısı"]="Promise count"
    ["Future işlemleri"]="Future operations"
    ["Promise işlemleri"]="Promise operations"
    ["Async Function işlemleri"]="Async Function operations"
    ["Await işlemleri"]="Await operations"
    ["Task işlemleri"]="Task operations"
    ["Executor işlemleri"]="Executor operations"
    ["Event Loop işlemleri"]="Event Loop operations"
    ["Async Runtime işlemleri"]="Async Runtime operations"
    ["Değer yok (null)"]="No value (null)"
    ["Değer var"]="Has value"
    ["Tip adı"]="Type name"
    ["Sonuç (0 veya 1)"]="Result (0 or 1)"
    ["Sağ operand (fallback)"]="Right operand (fallback)"
    ["Sonuç"]="Result"
    ["Üye ismi"]="Member name"
    ["İfade"]="Expression"
    ["Hata mesajı"]="Error message"
    ["API fonksiyonları"]="API functions"
    ["Optional operasyonları"]="Optional operations"
    ["Optional'ın değeri var mı?"]="Does optional have value?"
    ["Optional'dan değer al"]="Get value from optional"
    ["Optional'dan değer al veya default"]="Get value from optional or default"
    ["Optional için kod üret"]="Generate code for optional"
    ["Null kontrol için kod üret"]="Generate code for null check"
    ["Null-coalescing için kod üret"]="Generate code for null-coalescing"
    ["Safe navigation için kod üret"]="Generate code for safe navigation"
    ["Null assertion için kod üret"]="Generate code for null assertion"
    ["Optional oluştur"]="Create optional"
    ["Code generation fonksiyonları"]="Code generation functions"
    ["Yardımcı fonksiyonlar"]="Helper functions"
    ["Parser fonksiyonları - Stage 1'de implement edilecek"]="Parser functions - To be implemented in Stage 1"
    ["İlişkili değişken adı"]="Associated variable name"
    ["Stack'te ayır (hızlı, sınırlı)"]="Allocate on stack (fast, limited)"
    ["Heap'te ayır (yavaş, esnek)"]="Allocate on heap (slow, flexible)"
    ["Static/Global (program ömrü)"]="Static/Global (program lifetime)"
    ["Serbest bırakılacak değişken"]="Variable to free"
    ["Serbest bırakılacak adres"]="Address to free"
    ["Hedef değişken"]="Target variable"
    ["Kaynak değişken"]="Source variable"
    ["Sıfırlanacak değişken"]="Variable to zero"
    ["Sıfırlanacak boyut"]="Size to zero"
    ["Yeniden boyutlandırılacak değişken"]="Variable to resize"
    ["Bellek ayırma stratejileri"]="Memory allocation strategies"
    ["Bellek ayırma talebi"]="Memory allocation request"
    ["Bellek serbest bırakma"]="Memory deallocation"
    ["Bellek kopyalama"]="Memory copy"
    ["Bellek sıfırlama"]="Memory zeroing"
    ["Bellek yeniden boyutlandırma"]="Memory resizing"
    ["Bellek ayırma oluştur"]="Create memory allocation"
    ["Bellek serbest bırakma oluştur"]="Create memory deallocation"
    ["Bellek kopyalama oluştur"]="Create memory copy"
    ["Bellek sıfırlama oluştur"]="Create memory zeroing"
    ["Bellek yeniden boyutlandırma oluştur"]="Create memory resizing"
    ["Bellek ayırma için kod üret"]="Generate code for memory allocation"
    ["İşlenecek koleksiyon"]="Collection to process"
    ["Çağrılacak lambda"]="Lambda to call"
    ["Argümanlar"]="Arguments"
    ["Capture sayısı"]="Capture count"
    ["Label adı"]="Label name"
    ["Satır numarası"]="Line number"
    ["Koşul"]="Condition"
    ["Koşullu mu?"]="Is conditional?"
    ["Pause mesajı (optional)"]="Pause message (optional)"
    ["Then bloğu"]="Then block"
    ["Else bloğu (optional)"]="Else block (optional)"
    ["Goto içeriyor mu?"]="Contains goto?"
    ["Pause içeriyor mu?"]="Contains pause?"
    ["Label sayısı"]="Label count"
    ["Breakpoint sayısı"]="Breakpoint count"
    ["Paused mı?"]="Is paused?"
    ["Debug context operasyonları"]="Debug context operations"
    ["Debug goto operasyonları"]="Debug goto operations"
    ["Debug pause operasyonları"]="Debug pause operations"
    ["Debug print operasyonları"]="Debug print operations"
    ["Debug if operasyonları"]="Debug if operations"
    ["Yazma (üzerine yaz)"]="Write (overwrite)"
    ["Yazma/Okuma (sıfırdan)"]="Write/Read (from scratch)"
    ["Dosya işlemi"]="File operation"
    ["Dosya değişkeni"]="File variable"
    ["Okuma buffer'ı"]="Read buffer"
    ["Okunacak eleman sayısı"]="Element count to read"
    ["Yazılacak veri"]="Data to write"
    ["Yazılacak boyut"]="Size to write"
    ["Yazılacak eleman sayısı"]="Element count to write"
    ["Kapatılacak dosya değişkeni"]="File variable to close"
    ["Dosya konumlandırma (seek)"]="File positioning (seek)"
    ["Baştan"]="From beginning"
    ["Başlangıç noktası"]="Origin point"
    ["Dosya kontrolü"]="File check"
    ["Var mı? (runtime)"]="Exists? (runtime)"
    ["API fonksiyonları"]="API functions"
    ["Dosya işlemi oluştur"]="Create file operation"
    ["Dosya okuma oluştur"]="Create file read"
    ["Dosya yazma oluştur"]="Create file write"
    ["Dosya kapatma oluştur"]="Create file close"
    ["Dosya konumlandırma oluştur"]="Create file positioning"
    ["Dosya kontrolü oluştur"]="Create file check"
    ["Dosya açma için kod üret"]="Generate code for file open"
    ["Dosya okuma için kod üret"]="Generate code for file read"
    ["Dosya yazma için kod üret"]="Generate code for file write"
    ["Dosya kapatma için kod üret"]="Generate code for file close"
    ["Dosya konumlandırma için kod üret"]="Generate code for file positioning"
    ["Dosya kontrolü için kod üret"]="Generate code for file check"
    ["Dosya açma modları"]="File open modes"
)

# Files to process (most affected modules)
FILES=(
    "compiler/stage0/modules/async/async.h"
    "compiler/stage0/modules/async/async.c"
    "compiler/stage0/modules/async/async_codegen.c"
    "compiler/stage0/modules/async/async_codegen.h"
    "compiler/stage0/modules/async/async_parser.h"
    "compiler/stage0/modules/lambda/lambda.h"
    "compiler/stage0/modules/lambda/lambda.c"
    "compiler/stage0/modules/lambda/lambda_codegen.c"
    "compiler/stage0/modules/lambda/lambda_codegen.h"
    "compiler/stage0/modules/lambda/lambda_parser.h"
    "compiler/stage0/modules/lambda/lambda_standalone.c"
    "compiler/stage0/modules/memory/memory.h"
    "compiler/stage0/modules/memory/memory.c"
    "compiler/stage0/modules/memory/memory_codegen.c"
    "compiler/stage0/modules/memory/memory_codegen.h"
    "compiler/stage0/modules/memory/memory_parser.h"
    "compiler/stage0/modules/file_io/file_io.h"
    "compiler/stage0/modules/file_io/file_io.c"
    "compiler/stage0/modules/file_io/file_io_codegen.c"
    "compiler/stage0/modules/file_io/file_io_codegen.h"
    "compiler/stage0/modules/file_io/file_io_parser.c"
    "compiler/stage0/modules/file_io/file_io_parser.h"
    "compiler/stage0/modules/debug/debug_features.h"
    "compiler/stage0/modules/debug/debug_features.c"
    "compiler/stage0/modules/debug/debug_features_codegen.c"
    "compiler/stage0/modules/debug/debug_features_codegen.h"
    "compiler/stage0/modules/debug/debug_features_parser.c"
    "compiler/stage0/modules/debug/debug_features_parser.h"
    "compiler/stage0/modules/null_safety/null_safety.h"
    "compiler/stage0/modules/null_safety/null_safety.c"
    "compiler/stage0/modules/null_safety/null_safety_codegen.c"
    "compiler/stage0/modules/null_safety/null_safety_codegen.h"
    "compiler/stage0/modules/null_safety/null_safety_parser.h"
)

echo "🌍 Turkish → English Comment Translation"
echo "=========================================="
echo ""

TOTAL_FILES=${#FILES[@]}
PROCESSED=0
CHANGED=0

for file in "${FILES[@]}"; do
    if [ ! -f "$file" ]; then
        echo "⏭️  Skipped: $file (not found)"
        continue
    fi
    
    ((PROCESSED++))
    CHANGED_THIS_FILE=0
    
    # Create backup
    cp "$file" "$file.bak"
    
    # Apply translations
    for turkish in "${!TRANSLATIONS[@]}"; do
        english="${TRANSLATIONS[$turkish]}"
        
        # Replace in comments only (after //)
        if grep -q "$turkish" "$file"; then
            sed -i "s|// $turkish|// $english|g" "$file"
            sed -i "s|  // $turkish|  // $english|g" "$file"
            ((CHANGED_THIS_FILE++))
        fi
    done
    
    if [ $CHANGED_THIS_FILE -gt 0 ]; then
        ((CHANGED++))
        echo "✅ $file ($CHANGED_THIS_FILE translations)"
    else
        echo "⏭️  $file (no changes)"
        rm "$file.bak"
    fi
done

echo ""
echo "=========================================="
echo "📊 Summary:"
echo "   Files processed: $PROCESSED"
echo "   Files changed: $CHANGED"
echo "   Backups: *.bak files created"
echo ""
echo "✅ Translation complete!"
